server:
  port: 8082
spring:
  application:
    name: "ScaffoldQuickStart"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://autenticacion:8080"
jwt:
  secret: "u1FZ7xZkdlp7uPqFz3ME7J8Qz3YOXkU0jU6aWw+4/9uQ4dFw6Nw5Y8JtdfG2L/zzU7fNHbZx4fM="
  expiration: 3600
adapter:
  restconsumer:
    timeout: 5000
    url: "http://autenticacion:8080/api/v1"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "https://sqs.us-east-1.amazonaws.com"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/571202862746/ApprovedLoanApplicationQueue"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
aws:
  dynamodb:
    endpoint: "https://dynamodb.us-east-1.amazonaws.com"
  region: "us-east-1"
